source "https://rubygems.org"

gem "rails", "~> 7.1.3"

gem "sqlite3", ">= 2.8", platforms: [:windows]
gem "nokogiri", "~> 1.18", platforms: [:windows]

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[windows jruby]

gem "bootsnap", require: false
